services:
  - type: web
    name: barron-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: ALLOWED_ORIGINS
        value: "*"  # Cambia esto en producción si quieres restringir orígenes

